[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "/tmp/forge-std-check/lib"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=/tmp/forge-std-check/lib/forge-std/src/"
]
